
name: Build Android APK for Testing

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Sync Capacitor project
      run: |
        GEMINI_API_KEY=dummy_key_for_build \
        NEXT_PUBLIC_FIREBASE_API_KEY=dummy_key_for_build \
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=dummy.firebaseapp.com \
        NEXT_PUBLIC_FIREBASE_PROJECT_ID=dummy-project \
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=dummy.appspot.com \
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=1234567890 \
        NEXT_PUBLIC_FIREBASE_APP_ID=1:1234567890:web:dummyappid \
        npm run cap:sync

    - name: Build Android App with stacktrace
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
