
name: Build Android APK for Testing

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Configure App and Sync Capacitor
      env:
        # Pass the Vercel URL from GitHub secrets to the build script.
        # This is required so the Android app knows where to send AI requests.
        NEXT_PUBLIC_API_BASE_URL: ${{ secrets.VERCEL_URL }}
      run: |
        if [ -z "$NEXT_PUBLIC_API_BASE_URL" ]; then
          echo "Error: VERCEL_URL secret is not set."
          echo "Please add it to your repository secrets in GitHub Settings."
          exit 1
        fi
        npm run cap:sync

    - name: Build Android App with stacktrace
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
