
name: Build Android APK for Testing

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Create debug keystore
      run: |
        mkdir -p $HOME/.config/.android
        keytool -genkey -v \
          -keystore $HOME/.config/.android/debug.keystore \
          -alias androiddebugkey \
          -storepass android \
          -keypass android \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US"

    - name: Get Signing Report
      run: |
        cd android
        ./gradlew signingReport

    - name: Build and Sync Capacitor App
      env:
        # This secret must be set in your GitHub repository settings.
        # It should be the full URL of your deployed Vercel application.
        NEXT_PUBLIC_API_BASE_URL: ${{ secrets.VERCEL_URL }}
      run: |
        if [ -z "$NEXT_PUBLIC_API_BASE_URL" ]; then
          echo "Error: VERCEL_URL secret is not set."
          echo "Please add it to your repository secrets in GitHub Settings."
          exit 1
        fi
        # The cap:sync script runs the static build and syncs the native project.
        npm run cap:sync

    - name: Build Android App with stacktrace
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
